# steps:
#   # Build our Go Application
#   - name: 'gcr.io/cloud-builders/go'
#     args: ['build', '-o', 'server', '.']
#     env: ['PROJECT_NAME=main']
#
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/ta-chitchat-backend/chronicles-server', '.']
#
#   # Push the Container to Google Container Registry
#   - name: 'gcr.io/cloud-builders/kubectl'
#     args: ['apply', '-f', 'deployment.yaml']
#     env:
#       - 'CLOUDSDK_COMPUTE_ZONE=us-eastern5-a'
#       - 'CLOUDSDK_CONTAINER_CLUSTER=chronicle-cluster'
#
#   # Apply the Kubernetes Service
#   - name: 'gcr.io/cloud-builders/kubectl'
#     args: ['apply', '-f', 'service.yaml']
#     env:
#       - 'CLOUDSDK_COMPUTE_ZONE=us-eastern5-a'
#       - 'CLOUDSDK_CONTAINER_CLUSTER=chronicle-cluster'
#
# images:
#   - 'gcr.io/ta-chitchat-backend/chronicles-server'

steps:
  # Build Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/ta-chitchat-backend/chronicles-server", "."]

  # Push Container Image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/ta-chitchat-backend/chronicles-server"]

  # Deploy container Image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=ops/deployment.yaml
      - --image=gcr.io/ta-chitchat-backend/chronicles-server
      - --location=us-eastern5-a
      - --cluster=cluster-1
